print("please enter smallest side of triangle")
x=input()
print("please enter second smallest side of triangle")
y=input()
print("please enter the biggest side of triangle")
z=input()
print((int(x)+int(y))>int(z))
print("it's could be triangle if it's true and couldn't if false")