books=input("please enter the number of your books...")
print(int(books),"- soooo much? If you donate 5 books to library, your books quantity will be= ",int(books)-5)
print("did you read all these",int(books),"books?")
print("if you read only the half its will be =",int(books)/2)
scientific_articles=input("Please enter your scientific articles quantity...")
print(int(scientific_articles),"scientific articles are not bad, but you can be better")
age=input("How old are you?  ")
division=int(age)/int(scientific_articles)
print("if we divide your age on quantity of your articles we will receive",float(division),"that's mean that you are lazy :)))")
print("Bye bye be more productive!!!")